# Generated by Django 4.2.1 on 2023-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dish', models.TextField()),
                ('recipe', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('category', models.CharField(choices=[('RU', 'Русская кухня'), ('KZ', 'Казахская кухня'), ('USA', 'Американская кухня')], default='RU', max_length=128, verbose_name='Тип')),
            ],
        ),
    ]
